version: "3.8"

services:
  express-app:
    build: .
    container_name: express-app
    ports:
      - "5001:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express-app
